version: 0.2

phases:
  pre_build:
    commands:
      - echo installing
      - npm install
  build:
    commands:
      -echo run build
      - npm run build
 
artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build